bug class home page ( cant find "Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.thymeleaf.exceptions.TemplateInputException: An error happened during template parsing (template: "class path resource [templates//class_manager/classManagerHome.html]")] with root cause
                                 java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "to" is null")